"""Engine-agnostic export spike — prove a governed shard can feed another engine.

Strategic-fork probe (see the competitive-positioning note): RiskShard's real
moat is the *governed evidence*, not the Monte Carlo engine. If a shard's
frequency/impact triangle drops cleanly into a third-party FAIR engine, RiskShard
can be the evidence layer that feeds pyfair / CRML / commercial tools rather than
competing with them.

RiskShard's PERT triangle (frequency/impact min-likely-max) maps 1:1 onto the
BetaPert (low-mode-high) that pyfair's `input_data` expects — so this is a direct
translation, not an approximation. The exported artifact keeps a pointer back to
`provenance` so the evidence trail survives the hand-off. Read-only.
"""

PYFAIR_LEF = "Loss Event Frequency"
PYFAIR_LM = "Loss Magnitude"


def to_pyfair(scenario):
    """Map a scenario's frequency/impact PERT onto pyfair BetaPert inputs.

    Returns a dict of the two pyfair node inputs plus identity/currency, or raises
    ValueError if the PERT triangle is missing or malformed (low<=mode<=high).
    """
    name = scenario.get("metadata", {}).get("name") or scenario.get("id") or "RiskShard shard"
    currency = scenario.get("metadata", {}).get("currency")
    freq = scenario.get("frequency") or {}
    impact = scenario.get("impact") or {}

    def triangle(band, keys=("min", "likely", "max")):
        try:
            low, mode, high = (band[keys[0]], band[keys[1]], band[keys[2]])
        except (KeyError, TypeError):
            raise ValueError("scenario is missing a full min/likely/max triangle")
        if not (low <= mode <= high):
            raise ValueError(f"triangle out of order: {low} <= {mode} <= {high} is false")
        return {"low": low, "mode": mode, "high": high}

    return {
        "name": name,
        "currency": currency,
        PYFAIR_LEF: triangle(freq),
        PYFAIR_LM: triangle(impact),
    }


def format_pyfair_code(scenario, module_id=None):
    """A runnable pyfair snippet built from the shard, with a provenance pointer."""
    mapped = to_pyfair(scenario)
    lef, lm = mapped[PYFAIR_LEF], mapped[PYFAIR_LM]
    ref = module_id or mapped["name"]
    currency = f"  # currency: {mapped['currency']}" if mapped["currency"] else ""
    return "\n".join(
        [
            "# Generated by RiskShard (engine-agnostic export spike).",
            f"# Shard: {ref}. Every input below is governed evidence — trace it with:",
            f"#   python scripts/riskshard_modules.py provenance {module_id or '<shard>'}",
            "# RiskShard PERT (min/likely/max) maps 1:1 to pyfair BetaPert (low/mode/high).",
            "from pyfair import FairModel",
            "",
            f'model = FairModel(name={mapped["name"]!r})',
            f'model.input_data({PYFAIR_LEF!r}, low={lef["low"]}, mode={lef["mode"]}, high={lef["high"]})',
            f'model.input_data({PYFAIR_LM!r}, low={lm["low"]}, mode={lm["mode"]}, high={lm["high"]}){currency}',
            "model.calculate_all()",
            "print(model.export_results().head())",
            "",
        ]
    )
