"""Scaffold a new risk shard — the contributor on-ramp.

A shard is six wired files (module descriptor, scenario, org profile, calibration,
evidence, extractions). Assembling that plumbing by hand is the barrier to
contributing. `scaffold_shard` generates the whole set as an honestly-labelled
`scaffold` skeleton — every parameter is a placeholder estimate with a "replace
before use" caveat — so a contributor starts from a validating shard and only has
to do the real work: gather sources and replace the estimates. Nothing it writes
is presented as source-backed.
"""
from pathlib import Path

# Long taxonomy value -> short token used in shard ids (matches existing shards).
INDUSTRY_SHORT = {
    "financial_services": "finance",
    "manufacturing": "manufacturing",
    "healthcare": "health",
    "technology": "tech",
    "retail": "retail",
    "energy": "energy",
    "public_sector": "gov",
}
THREAT_SHORT = {
    "business_email_compromise": "bec",
    "data_breach": "data_breach",
    "ransomware": "ransomware",
    "insider_misuse": "insider",
    "third_party_outage": "third_party_outage",
    "ai_enabled_fraud": "ai_fraud",
}
REQUIRED_PARAMETERS = ("frequency.min", "frequency.likely", "frequency.max",
                       "impact.min", "impact.likely", "impact.max")
# Placeholder triangle so the skeleton runs; clearly not real numbers.
PLACEHOLDER = {
    "frequency.min": 0.01, "frequency.likely": 0.10, "frequency.max": 0.30,
    "impact.min": 10000, "impact.likely": 100000, "impact.max": 1000000,
}


def _size_squash(size):
    return str(size).replace("_", "")  # mid_market -> midmarket, matching house convention


def scaffold_id(country, industry, size, threat):
    ind = INDUSTRY_SHORT.get(industry, industry)
    thr = THREAT_SHORT.get(threat, threat)
    return f"{country.lower()}_{ind}_{thr}_{_size_squash(size)}"


def org_profile_stem(country, industry, size):
    ind = INDUSTRY_SHORT.get(industry, industry)
    return f"{country.lower()}_{ind}_{_size_squash(size)}"


def _titleize(s):
    return str(s).replace("_", " ").title()


def scaffold_paths(shard_id, country, industry, size):
    stem = shard_id
    return {
        "module": Path("risk_modules") / f"{stem}.yaml",
        "scenario": Path("scenarios") / f"{stem}.yaml",
        "org_profile": Path("org_profiles") / f"{org_profile_stem(country, industry, size)}.yaml",
        "calibration": Path("calibrations") / f"{stem}.yaml",
        "evidence": Path("evidence") / f"{stem}.yaml",
        "extractions": Path("extractions") / f"{stem}_reviewed.yaml",
    }


def _module_yaml(shard_id, country, industry, size, threat):
    tags = [country.lower(), industry, size, threat]
    return f"""id: {shard_id}
title: {_titleize(country)} {_titleize(industry)} {_titleize(threat)} {_titleize(size)}
version: "0.1"
status: scaffold
threat: {threat}
description: >
  SCAFFOLD shard generated by `new-shard`. Every parameter is a placeholder
  estimate, not evidence. Replace each with a source-backed value (gather
  sources, add evidence + extraction records) before using any number.
context:
  industry: {industry}
  country: {country}
  company_size: {size}
artifacts:
  scenario: scenarios/{shard_id}.yaml
  org_profile: org_profiles/{org_profile_stem(country, industry, size)}.yaml
  calibration: calibrations/{shard_id}.yaml
  evidence:
    - evidence/{shard_id}.yaml
  extractions:
    - extractions/{shard_id}_reviewed.yaml
  controls: []
required_parameters:
{chr(10).join(f'  - {p}' for p in REQUIRED_PARAMETERS)}
tags:
{chr(10).join(f'  - {t}' for t in tags)}
practitioner_notes:
  good_for: A starting skeleton to contribute a {_titleize(country)} {_titleize(industry)} {threat} shard.
  not_good_for: Any decision — every value is a placeholder until replaced with source-backed evidence.
"""


def _scenario_yaml(shard_id, country, industry, size, threat):
    return f"""metadata:
  name: {_titleize(country)} {_titleize(industry)} {_titleize(threat)} {_titleize(size)}
  version: "0.1"
  currency: USD
  scenario_stage: governed_starter
  benchmark_status: scaffold_placeholder_values
  description: >
    SCAFFOLD scenario. Placeholder frequency/impact triangle so the shard runs.
    Replace with calibrated, source-backed values before use.

frequency:
  min: {PLACEHOLDER['frequency.min']}
  likely: {PLACEHOLDER['frequency.likely']}
  max: {PLACEHOLDER['frequency.max']}

impact:
  min: {PLACEHOLDER['impact.min']}
  likely: {PLACEHOLDER['impact.likely']}
  max: {PLACEHOLDER['impact.max']}
"""


def _org_profile_yaml(country, industry, size):
    return f"""metadata:
  name: {_titleize(country)} {_titleize(size)} {_titleize(industry)}
  version: "0.1"

org_type: private_company
industry: {industry}
country: {_titleize(country)}
employees: 500
annual_revenue_or_budget: 100000000
data_sensitivity: moderate
internet_exposure: moderate
third_party_dependency: moderate
regulatory_intensity: moderate
"""


def _evidence_record(shard_id, parameter, country, industry, size, threat):
    rid = f"{shard_id}_{parameter.replace('.', '_')}_scaffold"
    return f"""  - id: {rid}
    title: SCAFFOLD placeholder for {parameter}
    parameter: {parameter}
    value: {PLACEHOLDER[parameter]}
    unit: {'annual_probability' if parameter.startswith('frequency') else 'currency'}
    source_name: RiskShard scaffold ({shard_id})
    source_type: model_assumption
    source_url_or_citation: SCAFFOLD placeholder pending reviewed {country} {industry} {threat} evidence.
    publication_date: "2026-01-01"
    extraction_date: "2026-01-01"
    extraction_notes: Placeholder generated by new-shard; replace with a real extracted value.
    normalization_notes: Not a real value. Replace before any use.
    limitations: SCAFFOLD placeholder, not source-backed. Replace before benchmark or decision use.
    confidence: low
    evidence_type: estimated
    applicability:
      industries: [{industry}]
      countries: [{country}]
      company_size_bands: [{size}]
      threats: [{threat}]"""


def _evidence_yaml(shard_id, country, industry, size, threat):
    records = "\n\n".join(
        _evidence_record(shard_id, p, country, industry, size, threat) for p in REQUIRED_PARAMETERS
    )
    return f"records:\n{records}\n"


def _calibration_yaml(shard_id, country, industry, size, threat):
    lines = [
        "metadata:",
        f"  name: {_titleize(country)} {_titleize(industry)} {_titleize(threat)} calibration",
        f"  scenario_name: {_titleize(country)} {_titleize(industry)} {_titleize(threat)} {_titleize(size)} - Calibrated Draft",
        '  version: "0.1"',
        "  notes: >",
        "    SCAFFOLD calibration. Each selector points at a placeholder estimate;",
        "    repoint to source-backed evidence ids as you add them.",
        "",
        "target_currency: USD",
        "",
        "parameters:",
    ]
    for group in ("frequency", "impact"):
        lines.append(f"  {group}:")
        for bound in ("min", "likely", "max"):
            rid = f"{shard_id}_{group}_{bound}_scaffold"
            lines.append(f"    {bound}:")
            lines.append(f"      evidence_id: {rid}")
            lines.append("      transform: direct")
            lines.append(f"      rationale: SCAFFOLD placeholder for {group}.{bound}; replace with source-backed evidence.")
    return "\n".join(lines) + "\n"


def _extractions_yaml(shard_id):
    # Extractions are optional for validation; ship an empty-but-valid file with guidance.
    return (
        "# SCAFFOLD extractions. Add one entry per source-backed evidence record you\n"
        "# create (source_id, cited line, value, unit, evidence_record_ids), then run\n"
        "# contributor_preflight.py. Placeholder estimates need no extraction entry.\n"
        "extractions: []\n"
    )


def scaffold_shard(root, country, industry, size, threat, *, dry_run=False, overwrite=False):
    """Generate the six wired files for a new shard. Returns a summary dict.

    Raises ValueError if the shard already exists (unless overwrite). With
    dry_run, returns the planned paths without writing.
    """
    root = Path(root)
    shard_id = scaffold_id(country, industry, size, threat)
    paths = scaffold_paths(shard_id, country, industry, size)

    module_path = root / paths["module"]
    if module_path.exists() and not overwrite:
        raise ValueError(f"Shard already exists: {paths['module']} (pass overwrite=True to replace)")

    content = {
        "module": _module_yaml(shard_id, country, industry, size, threat),
        "scenario": _scenario_yaml(shard_id, country, industry, size, threat),
        "org_profile": _org_profile_yaml(country, industry, size),
        "calibration": _calibration_yaml(shard_id, country, industry, size, threat),
        "evidence": _evidence_yaml(shard_id, country, industry, size, threat),
        "extractions": _extractions_yaml(shard_id),
    }

    written = []
    for key, rel in paths.items():
        target = root / rel
        if key == "org_profile" and target.exists():
            continue  # reuse an existing org profile rather than clobber it
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content[key], encoding="utf-8")
        written.append(str(rel))

    return {"shard_id": shard_id, "written": written, "dry_run": dry_run,
            "paths": {k: str(v) for k, v in paths.items()}}


def next_steps(shard_id):
    return [
        f"1. Inspect it:   python scripts/riskshard_modules.py coverage {shard_id}",
        f"2. Provenance:   python scripts/riskshard_modules.py provenance {shard_id}  (all placeholders)",
        "3. Gather a source and register it in sources/registry.yaml, then gather_sources.py.",
        f"4. Replace each estimate in evidence/{shard_id}.yaml with a source-backed record.",
        f"5. Add extraction entries in extractions/{shard_id}_reviewed.yaml for each source.",
        "6. Validate:     python scripts/contributor_preflight.py",
        "See docs/BENCHMARK_CONTRIBUTOR_WORKFLOW.md for the full path.",
    ]
