"""The published evidence report is what the generator produces from the live tree.

`docs/EVIDENCE_REPORT.md` is linked from the README as *"every parameter, with its source
and caveat"* — the page a reader opens to check a number against its source. It is
generated by `scripts/riskshard_modules.py provenance --all --report`, and regenerating
it is a step in the release runbook rather than anything automatic.

**It was five weeks stale when this test was written (2026-09-28).** The Australian
ransomware `impact.likely` anchor moved on 2026-08-23 — Sophos Australia 2025 to 2026,
USD 650,000 to 1,660,000 — and fourteen tests fired on that value. This report was not one
of them: it went on publishing `650000` against the 2025 edition, along with a
concentration figure of 97% that had since become 92%, through two releases and four QA
passes. Nothing read it, and the release step that regenerates it was simply not run.

That is the same defect as the calibration summary corrected in #199 on the same day, and
the same shape as the missing release archive in #202: **a generated artifact whose
generation is a manual step nobody checks.** The remedy the repo uses everywhere else is
to make the check fail, so this compares the committed file against a fresh render.

Deliberately an equality check and not a spot-check of one figure: the report is entirely
generated, so any difference at all means it is out of date, and a test that watched only
the numbers someone thought to list would have missed the caveat text that moved with the
anchor — which is most of what a reader is here for.
"""
import unittest
from pathlib import Path

from engine.provenance import build_portfolio_provenance, format_portfolio_markdown

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "EVIDENCE_REPORT.md"

REGENERATE = (
    "python scripts/riskshard_modules.py provenance --all "
    "--report docs/EVIDENCE_REPORT.md"
)


class EvidenceReportTests(unittest.TestCase):
    def test_the_committed_report_matches_a_fresh_render(self):
        self.assertTrue(REPORT.is_file(), f"{REPORT} is missing")
        expected = format_portfolio_markdown(build_portfolio_provenance(ROOT))
        actual = REPORT.read_text(encoding="utf-8")
        self.assertEqual(
            expected, actual,
            "docs/EVIDENCE_REPORT.md is out of date with the evidence it reports on — "
            f"regenerate it:\n    {REGENERATE}")

    def test_the_readme_still_sends_a_reader_here(self):
        """If the link goes, this guard is protecting a page nobody opens."""
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertIn("docs/EVIDENCE_REPORT.md", readme)


if __name__ == "__main__":
    unittest.main()
