import unittest
from pathlib import Path

from engine.doctor import build_doctor_report, format_doctor_report, parse_project_scripts


ROOT = Path(__file__).resolve().parents[1]


class DoctorTests(unittest.TestCase):
    def test_doctor_summarizes_local_readiness(self):
        report = build_doctor_report(ROOT)
        output = format_doctor_report(report)
        checks = {item["name"]: item for item in report["checks"]}

        # Every check passes except possibly the strength ledger, which is a
        # release-time property: on a working branch with evidence changes not yet cut
        # into a release, "not logged - record on release" is the correct answer. These
        # assertions used to require "pass" outright, and only held because test_cli runs
        # earlier in the suite and was appending the ledger entry as a side effect
        # (fixed 2026-07-31) -- the suite was satisfying its own assertion.
        self.assertIn(report["status"], {"pass", "needs_review"})
        self.assertEqual(
            [name for name, item in checks.items() if item["status"] != "pass"] or ["strength ledger"],
            ["strength ledger"],
        )
        # Every shard simulates the values its calibration produces. This check gates
        # since 2026-07-30: any new divergence means the published loss range would not
        # be generated by the evidence displayed beside it.
        self.assertEqual(checks["calibration drift"]["status"], "pass")
        # Coverage pin: 11 risk-module shards + 4 drift_watch top-risk pairs. If a
        # new calibrated scenario is added without joining either coverage path,
        # this count is the reminder (extended 2026-08-03 after the insider
        # scenario once drifted outside the gate's original coverage).
        self.assertIn("15 scenario/calibration pairs", checks["calibration drift"]["detail"])
        self.assertIn("pairs match", checks["calibration drift"]["detail"])
        self.assertIn("RiskShard doctor", output)
        self.assertEqual(checks["sources"]["status"], "pass")
        self.assertIn("governed_starter=15", checks["scenarios"]["detail"])
        self.assertIn("demo_fixture=5", checks["scenarios"]["detail"])
        self.assertEqual(checks["package entry points"]["status"], "pass")
        self.assertIn("run with --run-tests", checks["tests"]["detail"])
        # The ledger is either caught up or prompting for a release; both are valid.
        # Asserting "caught up" only held because the suite was appending the entry
        # itself (fixed 2026-07-31).
        self.assertIn(checks["strength ledger"]["status"], {"pass", "needs_review"})
        self.assertRegex(checks["strength ledger"]["detail"], r"caught up|record on release")

    def test_parse_project_scripts_reads_entry_points(self):
        text = """
[project.scripts]
riskshard = "scripts.fair_calc:main"
riskshard-doctor = "scripts.riskshard_doctor:main"

[tool.setuptools]
packages = ["engine"]
"""

        self.assertEqual(
            parse_project_scripts(text),
            ["riskshard", "riskshard-doctor"],
        )


if __name__ == "__main__":
    unittest.main()
